# Change these first
owner: alexbula # Your GitHub organization or username, where this repository lives
repo: test_status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: IAM Unagi
    url: https://iam.europe-west3.unagi.dev02.nttclouds.co/healthz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: wwwwwupptime.js.org
  baseUrl: /test_status
  logoUrl: https://raw.githubusercontent.com/AlexBula/test_status/master/assets/ntt.png
  apiBaseUrl: https://api.github.com
  name: Test Status Page
  introTitle: "**Test Status Page** build via upptime which is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Sample status page which uses **real-time** data. No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
