# Change these first
owner: alexbula # Your GitHub organization or username, where this repository lives
repo: test_status # The name of this repository

sites:
  - name: Iam Unagi
    url: https://iam.europe-west3.unagi.dev02.nttclouds.co/diagnostics/v1alpha:healthcheck
    method: GET
  - name: Applications Unagi
    url: https://applications.europe-west3.unagi.dev02.nttclouds.co/diagnostics/v1alpha:healthcheck
    method: GET
  - name: Devices Unagi
    url: https://devices.europe-west3.unagi.dev02.nttclouds.co/diagnostics/v1alpha:healthcheck
    method: GET
  - name: Audit Unagi
    url: https://audit.europe-west3.unagi.dev02.nttclouds.co/diagnostics/v1alpha:healthcheck
    method: GET
  - name: Limits Unagi
    url: https://limits.europe-west3.unagi.dev02.nttclouds.co/diagnostics/v1alpha:healthcheck
    method: GET
  - name: Logging Unagi
    url: https://logging.europe-west3.unagi.dev02.nttclouds.co/diagnostics/v1alpha:healthcheck
    method: GET
  - name: Meta Unagi
    url: https://meta.europe-west3.unagi.dev02.nttclouds.co/diagnostics/v1alpha:healthcheck
    method: GET
  - name: Monitoring Unagi
    url: https://monitoring.europe-west3.unagi.dev02.nttclouds.co/diagnostics/v1alpha:healthcheck
    method: GET
  - name: Proxies Unagi
    url: https://proxies.europe-west3.unagi.dev02.nttclouds.co/diagnostics/v1alpha:healthcheck
    method: GET
  - name: Secrets Unagi
    url: https://secrets.europe-west3.unagi.dev02.nttclouds.co/diagnostics/v1alpha:healthcheck
    method: GET
  - name: STG Smoke Tests
    url: https://api.github.com/repos/cloudwan/qa/actions/workflows/25360914/runs?per_page=1&page=1&status=completed
    method: GET
    headers:
      - "Accept: application/vnd.github+json"
      - "Authorization: Bearer $GH_PAT"
    __dangerous__body_down_if_text_missing: '"conclusion": "success"'



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: wwwwwupptime.js.org
  baseUrl: /test_status
  # cname: gohan.cloudwan.io
  logoUrl: https://raw.githubusercontent.com/AlexBula/test_status/master/assets/ntt.png
  apiBaseUrl: https://api.github.com
  name: Edgelq Status Page
  introTitle: "**About this site**."
  introMessage: The status page of the Edgelq Systems.

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
